apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mycert
  namespace: demo
spec:
  secretName: mycert-tls
  issuerRef:
    name: ca-issuer
  dnsNames:
  - '*.example.com'
  - example.com
  - foo.com

