apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ssl-config
  namespace: demo
data:
  ssl.conf: |
    server {
        listen 443 http2 ssl;
        server_name *.svc.cluster.local;

        ssl_certificate /tls/tls.crt;
        ssl_certificate_key /tls/tls.key;
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: "/tls"
          name: tls
        - mountPath: "/etc/nginx/conf.d"
          name: ssl-config
      volumes:
      - name: tls
        csi:
          readOnly: true
          driver: csi.cert-manager.io
          volumeAttributes:
            csi.cert-manager.io/issuer-name: mongo-ca-issuer
            csi.cert-manager.io/dns-names: nginx.demo.svc.cluster.local
      - name: ssl-config
        configMap:
          name: nginx-ssl-config
---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: demo
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
