apiVersion: v1
kind: Pod
metadata:
  name: my-csi-app
  namespace: demo
  labels:
    app: my-csi-app
spec:
  containers:
  - name: my-frontend
    image: busybox
    volumeMounts:
    - mountPath: "/tls"
      name: tls
    command: [ "sleep", "1000000" ]
  volumes:
  - name: tls
    csi:
      driver: csi.cert-manager.io
      volumeAttributes:
        csi.cert-manager.io/issuer-name: mongo-ca-issuer
        csi.cert-manager.io/dns-names: my-service.demo.svc.cluster.local
